services:
  authentication:
    build:
      context: ./authentication
    ports:
      - "4000:4000"
    volumes:
      - ./authentication:/app
      - /app/node_modules
    env_file:
      - ./authentication/.env

  nuxt:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
# Dockerize DB
#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_DB: expense_tracker_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:
